@baseUrl = http://localhost:3000

### Get Recados / All
GET {{baseUrl}}/recados
?page=3
&limit=2

### Get Recados / One byId
GET {{baseUrl}}/recados/1
Authorization: Bearer MyToken

### Post Recados
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Recado Teste",
  "deId": 2,
  "paraId": 3
}

### Put Recados / One byId
PUT {{baseUrl}}/recados/1a
Content-Type: application/json

{
  "texto": "Recado atualizado Post10",
  "lido": true
  //"deId": 2,
  //"paraId": 3
}

### Patch Recados / One byId
PATCH  {{baseUrl}}/recados/-1
Content-Type: application/json

{
  "texto": "Recado atualizado Post10",
  "lido": true
  //"deId": 2,
  //"paraId": 3
}

### Delete Recados / One byId
DELETE {{baseUrl}}/recados/a

#########################
### Pessoas
### Get Pessoas / All
GET {{baseUrl}}/pessoas
?page=1
&limit=1
Authorization: Bearer MyToken

### Get Pessoas / One byId
GET {{baseUrl}}/pessoas/51a
Authorization: Bearer MyToken

### Post Pessoas
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "email": "teste@teste.com.br",
  "nome": "Maria",
  "password": "Ab1@234"
}

### Patch Pessoas / One byId
PATCH {{baseUrl}}/pessoas/50
Content-Type: application/json

{
  "password": "234@Ab1"
}

### Delete Pessoas / One byId
DELETE {{baseUrl}}/pessoas/1
