# @name AppControllerGetHello
@baseUrl = http://localhost:3000
@exemplo = exemplo

### hello
GET {{baseUrl}}

### exemplo (cada comando precisa estar separado por 3#)
GET {{baseUrl}}/{{exemplo}}

### exemplo usando serviços
GET {{baseUrl}}/novo-exemplo

### manual controller
GET {{baseUrl}}/conceitos-manual

### manual controller consumindo service
GET {{baseUrl}}/conceitos-manual/soluciona-home

### automatico  controller
GET {{baseUrl}}/conceitos-automatico

### automatico controller consumindo service
GET {{baseUrl}}/conceitos-automatico/soluciona-home
