@baseUrl = http://localhost:3000

### Get Recados / All
GET {{baseUrl}}/recados
?page=1
&limit=10

### Get Recados / One byId
GET {{baseUrl}}/recados/3

### Post Recados
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Recado 3",
  "de": 50,
  "para": 51
}

### Put Recados / One byId
PUT {{baseUrl}}/recados/1
Content-Type: application/json

{
  "texto": "Recado atualizado Post10",
  "lido": true,
  "de": 51
}

### Delete Recados / One byId
DELETE {{baseUrl}}/recados/3

#########################
### Pessoas
### Get Pessoas / All
GET {{baseUrl}}/pessoas
?page=1
&limit=1

### Get Pessoas / One byId
GET {{baseUrl}}/pessoas/16

### Post Pessoas
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "email": "teste@teste.com.br",
  "nome": "Maria",
  "password": "Ab1@234"
}

### Patch Pessoas / One byId
PATCH {{baseUrl}}/pessoas/50
Content-Type: application/json

{
  "password": "234@Ab1"
}

### Delete Pessoas / One byId
DELETE {{baseUrl}}/pessoas/17
