@baseUrl = http://localhost:3000

### Get Recados / All
GET {{baseUrl}}/recados
?page=1
?limit=10

### Get Recados / One byId
GET {{baseUrl}}/recados/3

### Post Recados
POST {{baseUrl}}/recados
Content-Type: application/json

{
  "texto": "Recado 3",
  "de": "Maria",
  "para": "Pedro"
}

### Put Recados / One byId
PUT {{baseUrl}}/recados/5
Content-Type: application/json

{
  "texto": "Recado atualizado Post10",
  "lido": true,
  "de": "aaaaa"
}

### Delete Recados / One byId
DELETE {{baseUrl}}/recados/3
