@baseUrl = http://localhost:3000
@exemplo = exemplo

#Recados
@recadosController = recados
### findAll
GET {{baseUrl}}/{{recadosController}}

### findAll paginated
GET {{baseUrl}}/{{recadosController}}
?page=1
&limit=1

### findById
GET {{baseUrl}}/{{recadosController}}/3

### create reacado
POST {{baseUrl}}/{{recadosController}}
Content-Type: application/json

{
  "texto": "Recado 3",
  "de": "Maria",
  "para": "Pedro",
  "lido": false
}

### update recado
PATCH {{baseUrl}}/{{recadosController}}/1
Content-Type: application/json

{
    "id": 5,
    "texto": "recado atualizado a - oafensivo",
    "lido": true
}

### delete recado
DELETE {{baseUrl}}/{{recadosController}}/2

#########
#########
#########
#########
#########
#########
#########
#########
#########
#########
#########

### pagina recado
GET {{baseUrl}}/{{recadosController}}/pagina
?pagina=1
&limite=2

### pagina recado2 - com desestruturação
GET {{baseUrl}}/{{recadosController}}/pagina2
?pagina=1
&limite=2
&user=alexandre

### from service
GET {{baseUrl}}/{{recadosController}}/from-service
